In [19]:
import torch
import numpy as np

In [6]:
x = torch.randn(3,4,requires_grad=True)
x

tensor([[ 1.1599,  0.0941, -0.3973, -0.8031],
        [-1.3041,  1.4453, -0.8164,  0.8761],
        [-0.5660,  0.1190,  0.3687,  1.4805]], requires_grad=True)

In [7]:
b = torch.randn(3,4,requires_grad=True)

In [8]:
t = x+b

In [10]:
y = t.sum()
y

tensor(-1.9371, grad_fn=<SumBackward0>)

In [11]:
y.backward()

In [12]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
x = torch.rand(1)
b = torch.rand(1,requires_grad=True)
w = torch.rand(1,requires_grad=True)
y = w*x
z = y+b

In [14]:
x.requires_grad,b.requires_grad,w.requires_grad,y.requires_grad

(False, True, True, True)

In [15]:
z.backward(retain_graph=True)

In [16]:
w.grad

tensor([0.2541])

In [17]:
b.grad

tensor([1.])

In [21]:
x_values = [i for i in range(11)]
x_train = np.array(x_values,dtype=np.float32)
x_train = x_train.reshape(-1,1)
x_train.shape

(11, 1)

In [23]:
y_values = [2*i+1 for i in x_values]
y_train = np.array(y_values,dtype=np.float32)
y_train = y_train.reshape(-1,1)
y_train.shape

(11, 1)

In [24]:
import torch.nn as nn

In [28]:
class LinearRegressionModel(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(LinearRegressionModel,self).__init__()
        self.linear = nn.Linear(input_dim,output_dim)
        
    def forward(self,x):
        out = self.linear(x)
        return out

In [29]:
input_dim=1
output_dim=1

model = LinearRegressionModel(input_dim,output_dim)

In [30]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [31]:
epochs = 1000
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
criterion = nn.MSELoss()

In [35]:
for epoch in range(epochs):
    epoch += 1
    inputs = torch.from_numpy(x_train)
    labels = torch.from_numpy(y_train)
    
    optimizer.zero_grad()
    
    outputs = model(inputs)
    loss = criterion(outputs,labels)
    loss.backward()
    
    optimizer.step()
    if epoch % 50 ==0:
        print("epoch {}, loss {}".format(epoch,loss.item()))

epoch 50, loss 1.5593505653388462e-11
epoch 100, loss 1.5593505653388462e-11
epoch 150, loss 1.5593505653388462e-11
epoch 200, loss 1.5593505653388462e-11
epoch 250, loss 1.5593505653388462e-11
epoch 300, loss 1.5593505653388462e-11
epoch 350, loss 1.5593505653388462e-11
epoch 400, loss 1.5593505653388462e-11
epoch 450, loss 1.5593505653388462e-11
epoch 500, loss 1.5593505653388462e-11
epoch 550, loss 1.5593505653388462e-11
epoch 600, loss 1.5593505653388462e-11
epoch 650, loss 1.5593505653388462e-11
epoch 700, loss 1.5593505653388462e-11
epoch 750, loss 1.5593505653388462e-11
epoch 800, loss 1.5593505653388462e-11
epoch 850, loss 1.5593505653388462e-11
epoch 900, loss 1.5593505653388462e-11
epoch 950, loss 1.5593505653388462e-11
epoch 1000, loss 1.5593505653388462e-11


In [37]:
predicted = model(torch.from_numpy(x_train).requires_grad_()).data.numpy()
predicted

array([[ 0.99999267],
       [ 2.9999938 ],
       [ 4.999995  ],
       [ 6.9999967 ],
       [ 8.999997  ],
       [10.999998  ],
       [13.        ],
       [15.000001  ],
       [17.000002  ],
       [19.000004  ],
       [21.000004  ]], dtype=float32)

In [41]:
torch.save(model.state_dict(),'model.pkl')

In [42]:
model.load_state_dict(torch.load('model.pkl'))

<All keys matched successfully>